version: '3.7'

services:
  # app server (gunicorn)
  app:
    build: ./django
    volumes:
      #- ./app/:/usr/src/app/
      - static_volume:/code/hello/staticfiles
      - media_volume:/code/hello/mediafiles
    depends_on:
      - db
    # ports:
    #   - 8000:8000
    networks:
      - network_db
      - network_nginx

  # database server (postgresql)
  db:
    build: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - network_db
      - network_dba

  # database admin panel (pgadmin4)
  dba:
    build: ./dba
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@mail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin@pg123'
    depends_on:
      - db
    ports:
      - 8111:80
    networks:
      - network_dba

  # web server (nginx)
  web:
    build: ./nginx
    volumes:
      - static_volume:/code/hello/staticfiles
      - media_volume:/code/hello/mediafiles
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    ports:
      - 1337:8000
    depends_on:
      - app
    networks:
      - network_nginx

# create a network
networks:
  network_db:
    driver: bridge
  network_dba:
    driver: bridge
  network_nginx:
    driver: bridge

# volumes
volumes:
  pgdata:
  static_volume:
  media_volume:
