version: '3.7'

services:
  # app server (gunicorn)
  app:
    build: ./django
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - network_db
      - network_nginx

  # database server (postgresql)
  db:
    build: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    # ports:
    #   - 5432:5432
    networks:
      - network_db

  # database admin panel (pgadmin4)
  dba:
    build: ./dba
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@mail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin@pg123'
    depends_on:
      - db
    ports:
      - 8111:80
    networks:
      - network_db

  # web server (nginx)
  web:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - db
    networks:
      - network_nginx

# create a network
networks:
  network_db:
    driver: bridge
  network_nginx:
    driver: bridge

# volumes
volumes:
  pgdata:
